%% Parameters
env_parameters = struct('NEIGHBOR_THRESHOLD', 2.00, ...     % Road 2.00   Text 2.20
                        'NR_LOC', 0, ...
                        'NR_AGENT', 25, ...
                        'NR_OBFLOC', 100, ... 
                        'NR_TASK', 1, ...
                        'ALPHA', 100, ...
                        'EPSILON', 10.0, ...             % Road 10.0   Text 10.0
                        'DELTA', 0.01, ...
                        'REGION_SCALE', 20, ... 
                        'NR_NODE_IN_TARGET', 500, ...       % Road 500 Text 500
                        'ITER', 10, ...
                        'obf_loc', [], ...
                        'cost_matrix', []); 
